<?php
/**
 * EstimateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Armada\SDK\Generated
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Armada Automated Ordering API
 *
 * The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request's category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@armadadelivery.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Armada\SDK\Generated\Model;

use \ArrayAccess;
use \Armada\SDK\Generated\ObjectSerializer;

/**
 * EstimateRequest Class Doc Comment
 *
 * @category Class
 * @package  Armada\SDK\Generated
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EstimateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EstimateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'originFormat' => 'string',
        'origin' => '\Armada\SDK\Generated\Model\DeliveryRequestOrigin',
        'destinationFormat' => 'string',
        'destination' => '\Armada\SDK\Generated\Model\DeliveryRequestDestination'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'originFormat' => null,
        'origin' => null,
        'destinationFormat' => null,
        'destination' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'originFormat' => false,
        'origin' => false,
        'destinationFormat' => false,
        'destination' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'originFormat' => 'origin_format',
        'origin' => 'origin',
        'destinationFormat' => 'destination_format',
        'destination' => 'destination'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'originFormat' => 'setOriginFormat',
        'origin' => 'setOrigin',
        'destinationFormat' => 'setDestinationFormat',
        'destination' => 'setDestination'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'originFormat' => 'getOriginFormat',
        'origin' => 'getOrigin',
        'destinationFormat' => 'getDestinationFormat',
        'destination' => 'getDestination'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ORIGIN_FORMAT_LOCATION_FORMAT = 'location_format';
    public const ORIGIN_FORMAT_BRANCH_FORMAT = 'branch_format';
    public const DESTINATION_FORMAT_LOCATION_FORMAT = 'location_format';
    public const DESTINATION_FORMAT_KUWAIT_FORMAT = 'kuwait_format';
    public const DESTINATION_FORMAT_BAHRAIN_FORMAT = 'bahrain_format';
    public const DESTINATION_FORMAT_KSA_FORMAT = 'ksa_format';
    public const DESTINATION_FORMAT_KSA_SHORT_FORMAT = 'ksa_short_format';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOriginFormatAllowableValues()
    {
        return [
            self::ORIGIN_FORMAT_LOCATION_FORMAT,
            self::ORIGIN_FORMAT_BRANCH_FORMAT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDestinationFormatAllowableValues()
    {
        return [
            self::DESTINATION_FORMAT_LOCATION_FORMAT,
            self::DESTINATION_FORMAT_KUWAIT_FORMAT,
            self::DESTINATION_FORMAT_BAHRAIN_FORMAT,
            self::DESTINATION_FORMAT_KSA_FORMAT,
            self::DESTINATION_FORMAT_KSA_SHORT_FORMAT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('originFormat', $data ?? [], null);
        $this->setIfExists('origin', $data ?? [], null);
        $this->setIfExists('destinationFormat', $data ?? [], null);
        $this->setIfExists('destination', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['originFormat'] === null) {
            $invalidProperties[] = "'originFormat' can't be null";
        }
        $allowedValues = $this->getOriginFormatAllowableValues();
        if (!is_null($this->container['originFormat']) && !in_array($this->container['originFormat'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'originFormat', must be one of '%s'",
                $this->container['originFormat'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['origin'] === null) {
            $invalidProperties[] = "'origin' can't be null";
        }
        if ($this->container['destinationFormat'] === null) {
            $invalidProperties[] = "'destinationFormat' can't be null";
        }
        $allowedValues = $this->getDestinationFormatAllowableValues();
        if (!is_null($this->container['destinationFormat']) && !in_array($this->container['destinationFormat'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'destinationFormat', must be one of '%s'",
                $this->container['destinationFormat'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['destination'] === null) {
            $invalidProperties[] = "'destination' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets originFormat
     *
     * @return string
     */
    public function getOriginFormat()
    {
        return $this->container['originFormat'];
    }

    /**
     * Sets originFormat
     *
     * @param string $originFormat originFormat
     *
     * @return self
     */
    public function setOriginFormat($originFormat)
    {
        if (is_null($originFormat)) {
            throw new \InvalidArgumentException('non-nullable originFormat cannot be null');
        }
        $allowedValues = $this->getOriginFormatAllowableValues();
        if (!in_array($originFormat, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'originFormat', must be one of '%s'",
                    $originFormat,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['originFormat'] = $originFormat;

        return $this;
    }

    /**
     * Gets origin
     *
     * @return \Armada\SDK\Generated\Model\DeliveryRequestOrigin
     */
    public function getOrigin()
    {
        return $this->container['origin'];
    }

    /**
     * Sets origin
     *
     * @param \Armada\SDK\Generated\Model\DeliveryRequestOrigin $origin origin
     *
     * @return self
     */
    public function setOrigin($origin)
    {
        if (is_null($origin)) {
            throw new \InvalidArgumentException('non-nullable origin cannot be null');
        }
        $this->container['origin'] = $origin;

        return $this;
    }

    /**
     * Gets destinationFormat
     *
     * @return string
     */
    public function getDestinationFormat()
    {
        return $this->container['destinationFormat'];
    }

    /**
     * Sets destinationFormat
     *
     * @param string $destinationFormat destinationFormat
     *
     * @return self
     */
    public function setDestinationFormat($destinationFormat)
    {
        if (is_null($destinationFormat)) {
            throw new \InvalidArgumentException('non-nullable destinationFormat cannot be null');
        }
        $allowedValues = $this->getDestinationFormatAllowableValues();
        if (!in_array($destinationFormat, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'destinationFormat', must be one of '%s'",
                    $destinationFormat,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['destinationFormat'] = $destinationFormat;

        return $this;
    }

    /**
     * Gets destination
     *
     * @return \Armada\SDK\Generated\Model\DeliveryRequestDestination
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param \Armada\SDK\Generated\Model\DeliveryRequestDestination $destination destination
     *
     * @return self
     */
    public function setDestination($destination)
    {
        if (is_null($destination)) {
            throw new \InvalidArgumentException('non-nullable destination cannot be null');
        }
        $this->container['destination'] = $destination;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


